### ISSUE TITLE
Great tool! Some improvement suggestions. 

### ISSUE THREAD

**Issue by com2** [xurizaemon/org.civicrm.contrib.anonymize#11]
Really thank you for this extension! I have to develop on some sensitive personal data and this works for now. There are however some details that could be improved. 

- certain fields hold crucial information for a developer but are anonymized or removed. If anonymization is consistent (hashing, no randomization ), then the crucial string can still be recognised. Deleting however  is fatal. For instance Relationship description field is deleted where in my project is stored some very handy information. 
- After anonymizing the search for non-deceased contacts stopped working, always returning zero results. 
- I think I don't agree that anonymizing is that you let contacts randomly die, because that seems to have happened here with my dataset. I can agree that the decease date is changed when it is there, but a contact that is alive should remain alive.

**Comment by xurizaemon** [comment]
All good suggestions. If you wish to tackle any of them, I'm happy to accept fixes/improvements.

The best way to do this is to submit an issue and/or PR for each individual change (probably two PR above, perhaps one for a way to flag data you want to scramble or remove, and one to address the random assignment of is_deceased flags).

Really helpful if you [submit changes as PR](https://help.github.com/articles/creating-a-pull-request-from-a-fork/), but I appreciate your fixes however you submit them 😁

**Comment by xurizaemon** [comment]
Moved the deceased issues to #14

**Comment by xurizaemon** [comment]
Closing Github issues, moving to https://lab.civicrm.org/xurizaemon/org.civicrm.contrib.anonymize/-/issues - issue number will be the same there!
